on0: true
on1: false
on2: false
on3: false
motion: false
texture: false
twoSide: false
modelLocal: false
changeView: true
rotX: -430
rotY: 605
rotZ: 0
transX: 151.370071
transY: 182.413513
transZ: -294.8909
speedX: 1
speedY: 1
speedZ: 0
vertNum: 100
spinAngle: 35
layers: 5