on0: true
on1: false
on2: false
on3: false
texture: true
motion: false
twoSide: false
modelLocal: false
changeView: true
rotX: -35
rotY: 0
rotZ: 0
transX: 18.6558704
transY: 51.5035896
transZ: 0
speedX: 1
speedY: 1
speedZ: 0
vertNum: 4
spinAngle: 135
layers: 50